export const ADD_PRODUCT = 'ADD_PRODUCT';
export const SUCCESS_PRODUCT='SUCCESS_PRODUCT';
export const ERROR_PRODUCT='ERROR_PRODUCT';

export const ADD_DOWNLOAD ='ADD_DOWNLOAD'
export const SUCCESS_DOWNLOAD ='SUCCESS_DOWNLOAD'
export const ERROR_DOWNLOAD ='ERROR_DOWNLOAD'

export const GET_ELIMINATED ='GET_ELIMINATED'
export const SUCCESS_ELIMINATED ='SUCCESS_ELIMINATED'
export const ERROR_ELIMINATED ='ERROR_ELIMINATED'

export const GET_EDITED ='GET_EDITED'
export const SUCCESS_EDITED ='SUCCESS_EDITED'
export const ERROR_EDITED ='ERROR_EDITED'
export const START_EDITED ='START_EDITED'

export const SHOW_ALERT ='SHOW_ALERT'
export const HIDE_ALERT='HIDE_ALERT'